#!/bin/bash
sudo apt-get install auditd -y
sudo systemctl start auditd
sudo systemctl enable auditd

echo "setting up audits..."

sudo auditctl -a always,exit -F perm=x -F auid>=1000 -F dir=/usr -F dir=/etc -F dir=/bin -k suid_monitor
sudo auditctl -w /etc/passwd -p rwxa -k passwd_changes
sudo auditctl -w /etc/group -p rwxa -k group_changes
sudo auditctl -w /etc/shadow -p rwxa -k passwd_changes

se status
sed -i 's/^SELINUX=.*/SELINUX=enfocing/' /etc/selinux/config
echo "SELINUX set to enforcing"

sed -i 's/^KillUserProcesses=.*/KillUserProcesses=yes/' /etc/systemd/logind.conf
echo "Processes are killed on user logout"

iptables -t filter --append INPUT -j DROP 
iptables -t filter --delete INPUT 2 
iptables -t filter --check INPUT -s 192.168.1.123 -j DROP 
iptables -t filter -A INPUT -p udp -j DROP 
iptables -t filter -A INPUT -s 192.168.1.230 -j ACCEPT 
