#!/bin/bash
find / -perm /6000 2>/dev/null | while read -r file; do
    echo "removing SUID or SGID bit from $file"
    chmod u-s,g-s "$file"
done
find / -perm -o=w 2>/dev/null | while read -r file; do
    echo "removing world-writables from $file"
    chmod o-w "$file"
done
